import { getCurrentIdToken } from './authToken';

/**
 * Email Service — Frontend client for the /api/send-report serverless function
 */

function getSendReportUrl() {
  const apiBase = import.meta.env.VITE_API_BASE_URL?.trim();

  if (apiBase) {
    return new URL('/api/send-report', apiBase).toString();
  }

  return '/api/send-report';
}

export async function sendReportEmail(to, projectInfo, attachments = []) {
  try {
    const token = await getCurrentIdToken();
    if (!token) {
      return { success: false, error: 'Please sign in before sending a report email.' };
    }

    const response = await fetch(getSendReportUrl(), {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({
        to,
        projectName: projectInfo.name,
        totalValue: projectInfo.totalValue,
        attachments,
      }),
    });

    const raw = await response.text();
    let data = {};

    try {
      data = raw ? JSON.parse(raw) : {};
    } catch {
      data = { error: raw || 'Failed to send email' };
    }

    if (!response.ok) {
      return { success: false, error: data.error || 'Failed to send email' };
    }

    return { success: true, id: data.id };
  } catch (err) {
    console.error('Email service error:', err);
    const isLocalDev = typeof window !== 'undefined' && ['localhost', '127.0.0.1'].includes(window.location.hostname);
    return {
      success: false,
      error: isLocalDev
        ? 'Email endpoint could not be reached from local dev. Set VITE_API_BASE_URL to your deployed backend URL or run the app from its deployed host.'
        : 'Network error. Please check your connection and try again.',
    };
  }
}

/**
 * Generate a plain-text project summary for sharing via WhatsApp / clipboard
 */
export function generateShareText(projectInfo, sections = []) {
  const grandTotal = sections.reduce(
    (acc, s) => acc + (s.items || []).reduce((sum, i) => sum + (i.total || 0), 0),
    0
  );

  const sectionLines = sections
    .map((s, idx) => {
      const sTotal = (s.items || []).reduce((sum, i) => sum + (i.total || 0), 0);
      return `  ${String.fromCharCode(65 + idx)}. ${s.title} — ₦${sTotal.toLocaleString()}`;
    })
    .join('\n');

  return [
    `📋 *BOQ REPORT*`,
    `━━━━━━━━━━━━━━━━`,
    `*Project:* ${projectInfo.name}`,
    `*Client:* ${projectInfo.client || 'N/A'}`,
    `*Date:* ${projectInfo.date || new Date().toLocaleDateString()}`,
    ``,
    `*Section Breakdown:*`,
    sectionLines || '  No sections yet',
    ``,
    `━━━━━━━━━━━━━━━━`,
    `*ESTIMATED CONTRACT SUM:* ₦${grandTotal.toLocaleString()}`,
    ``,
    `_Generated by BOQ Pro Enterprise_`,
  ].join('\n');
}

/**
 * Share via WhatsApp — opens wa.me with the project summary
 */
export function shareViaWhatsApp(projectInfo, sections = []) {
  const text = generateShareText(projectInfo, sections);
  const encoded = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${encoded}`, '_blank');
}

/**
 * Share via Web Share API (native device share sheet)
 * Returns true if successful, false if not supported or cancelled
 */
export async function shareViaNative(projectInfo, sections = [], pdfBlob = null) {
  if (!navigator.share) {
    return { success: false, error: 'Native sharing is not supported on this device.' };
  }

  const text = generateShareText(projectInfo, sections);

  const shareData = {
    title: `BOQ Report: ${projectInfo.name}`,
    text: text,
  };

  // If we have a PDF blob, attach it as a file
  if (pdfBlob && navigator.canShare) {
    const file = new File([pdfBlob], `${projectInfo.name.replace(/\s+/g, '_')}_BOQ.pdf`, {
      type: 'application/pdf',
    });
    const dataWithFile = { ...shareData, files: [file] };
    if (navigator.canShare(dataWithFile)) {
      shareData.files = [file];
    }
  }

  try {
    await navigator.share(shareData);
    return { success: true };
  } catch (err) {
    if (err.name === 'AbortError') {
      return { success: false, error: 'Share cancelled' };
    }
    return { success: false, error: err.message };
  }
}

/**
 * Copy project summary text to clipboard
 */
export async function copyShareTextToClipboard(projectInfo, sections = []) {
  const text = generateShareText(projectInfo, sections);
  try {
    await navigator.clipboard.writeText(text);
    return { success: true };
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return { success: true };
  }
}
