/**
 * Email Service — Frontend client for the /api/send-report serverless function
 */

export async function sendReportEmail(to, projectInfo, attachments = []) {
  try {
    const response = await fetch('/api/send-report', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        to,
        projectName: projectInfo.name,
        totalValue: projectInfo.totalValue,
        attachments,
      }),
    });

    const data = await response.json();

    if (!response.ok) {
      return { success: false, error: data.error || 'Failed to send email' };
    }

    return { success: true, id: data.id };
  } catch (err) {
    console.error('Email service error:', err);
    return {
      success: false,
      error: 'Network error. Please check your connection and try again.',
    };
  }
}

/**
 * Generate a plain-text project summary for sharing via WhatsApp / clipboard
 */
export function generateShareText(projectInfo, sections = []) {
  const grandTotal = sections.reduce(
    (acc, s) => acc + (s.items || []).reduce((sum, i) => sum + (i.total || 0), 0),
    0
  );

  const sectionLines = sections
    .map((s, idx) => {
      const sTotal = (s.items || []).reduce((sum, i) => sum + (i.total || 0), 0);
      return `  ${String.fromCharCode(65 + idx)}. ${s.title} — ₦${sTotal.toLocaleString()}`;
    })
    .join('\n');

  return [
    `📋 *BOQ REPORT*`,
    `━━━━━━━━━━━━━━━━`,
    `*Project:* ${projectInfo.name}`,
    `*Client:* ${projectInfo.client || 'N/A'}`,
    `*Date:* ${projectInfo.date || new Date().toLocaleDateString()}`,
    ``,
    `*Section Breakdown:*`,
    sectionLines || '  No sections yet',
    ``,
    `━━━━━━━━━━━━━━━━`,
    `*ESTIMATED CONTRACT SUM:* ₦${grandTotal.toLocaleString()}`,
    ``,
    `_Generated by BOQ Pro Enterprise_`,
  ].join('\n');
}

/**
 * Share via WhatsApp — opens wa.me with the project summary
 */
export function shareViaWhatsApp(projectInfo, sections = []) {
  const text = generateShareText(projectInfo, sections);
  const encoded = encodeURIComponent(text);
  window.open(`https://wa.me/?text=${encoded}`, '_blank');
}

/**
 * Share via Web Share API (native device share sheet)
 * Returns true if successful, false if not supported or cancelled
 */
export async function shareViaNative(projectInfo, sections = [], pdfBlob = null) {
  if (!navigator.share) {
    return { success: false, error: 'Native sharing is not supported on this device.' };
  }

  const text = generateShareText(projectInfo, sections);

  const shareData = {
    title: `BOQ Report: ${projectInfo.name}`,
    text: text,
  };

  // If we have a PDF blob, attach it as a file
  if (pdfBlob && navigator.canShare) {
    const file = new File([pdfBlob], `${projectInfo.name.replace(/\s+/g, '_')}_BOQ.pdf`, {
      type: 'application/pdf',
    });
    const dataWithFile = { ...shareData, files: [file] };
    if (navigator.canShare(dataWithFile)) {
      shareData.files = [file];
    }
  }

  try {
    await navigator.share(shareData);
    return { success: true };
  } catch (err) {
    if (err.name === 'AbortError') {
      return { success: false, error: 'Share cancelled' };
    }
    return { success: false, error: err.message };
  }
}

/**
 * Copy project summary text to clipboard
 */
export async function copyShareTextToClipboard(projectInfo, sections = []) {
  const text = generateShareText(projectInfo, sections);
  try {
    await navigator.clipboard.writeText(text);
    return { success: true };
  } catch {
    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.opacity = '0';
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return { success: true };
  }
}
