import { Resend } from 'resend';

export default async function handler(req, res) {
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    return res.status(500).json({
      error: 'Email service not configured. Add RESEND_API_KEY to your Vercel environment variables.'
    });
  }

  const resend = new Resend(apiKey);

  try {
    const { to, projectName, totalValue, attachments } = req.body;

    if (!to || !projectName) {
      return res.status(400).json({ error: 'Missing required fields: to, projectName' });
    }

    // Build attachment objects for Resend
    const resendAttachments = (attachments || []).map(att => ({
      filename: att.filename,
      content: Buffer.from(att.content, 'base64'),
    }));

    const fromAddress = process.env.RESEND_FROM_EMAIL || 'BOQ Pro <onboarding@resend.dev>';

    const { data, error } = await resend.emails.send({
      from: fromAddress,
      to: [to],
      subject: `BOQ Report: ${projectName}`,
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f8fafc; padding: 0;">
          <!-- Header -->
          <div style="background: #0f172a; padding: 32px 24px; text-align: center;">
            <h1 style="color: white; margin: 0; font-size: 20px; font-weight: 800; letter-spacing: 0.02em;">
              BOQ PRO
            </h1>
            <p style="color: #64748b; margin: 4px 0 0; font-size: 12px;">
              Digital Engineering Standards Platform
            </p>
          </div>

          <!-- Body -->
          <div style="padding: 32px 24px;">
            <h2 style="color: #0f172a; font-size: 18px; margin: 0 0 8px;">
              Bill of Quantities Report
            </h2>
            <p style="color: #64748b; font-size: 14px; line-height: 1.6; margin: 0 0 24px;">
              Please find attached the BOQ report for the project detailed below.
            </p>

            <!-- Project Card -->
            <div style="background: white; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
              <div style="margin-bottom: 12px;">
                <span style="font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em;">
                  PROJECT
                </span>
                <p style="font-size: 16px; font-weight: 700; color: #0f172a; margin: 4px 0 0;">
                  ${projectName}
                </p>
              </div>
              ${totalValue ? `
              <div style="border-top: 1px solid #f1f5f9; padding-top: 12px;">
                <span style="font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em;">
                  ESTIMATED CONTRACT SUM
                </span>
                <p style="font-size: 20px; font-weight: 800; color: #2563eb; margin: 4px 0 0;">
                  ₦${Number(totalValue).toLocaleString()}
                </p>
              </div>
              ` : ''}
            </div>

            ${resendAttachments.length > 0 ? `
            <p style="color: #64748b; font-size: 13px; margin: 0 0 4px;">
              📎 <strong>${resendAttachments.length}</strong> file(s) attached
            </p>
            ` : ''}
          </div>

          <!-- Footer -->
          <div style="background: #f1f5f9; border-top: 1px solid #e2e8f0; padding: 16px 24px; text-align: center;">
            <p style="color: #94a3b8; font-size: 11px; margin: 0;">
              Generated by BOQ Pro Enterprise • Digital Engineering Standards
            </p>
          </div>
        </div>
      `,
    });

    if (error) {
      console.error('Resend error:', error);
      return res.status(500).json({ error: error.message || 'Failed to send email' });
    }

    return res.status(200).json({ success: true, id: data?.id });
  } catch (err) {
    console.error('Send report error:', err);
    return res.status(500).json({ error: err.message || 'Internal server error' });
  }
}
