/* global process */
import { Resend } from 'resend';
import { requireFirebaseAuth } from './_lib/firebase-auth.js';

const REPORT_LIMIT_WINDOW_MS = 60 * 60 * 1000;
const REPORT_LIMIT_MAX_REQUESTS = 5;
const reportRateLimitMap = new Map();

const EMAIL_REGEX = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

function escapeHtml(value = '') {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function getClientIp(req) {
  return String(req.headers['x-forwarded-for'] || req.socket?.remoteAddress || '')
    .split(',')[0]
    .trim();
}

function checkReportRateLimit(identity) {
  const now = Date.now();
  const entry = reportRateLimitMap.get(identity);

  if (entry && now - entry.windowStart < REPORT_LIMIT_WINDOW_MS) {
    if (entry.count >= REPORT_LIMIT_MAX_REQUESTS) {
      return { allowed: false, retryAfterMs: REPORT_LIMIT_WINDOW_MS - (now - entry.windowStart) };
    }

    entry.count += 1;
    return { allowed: true };
  }

  reportRateLimitMap.set(identity, { windowStart: now, count: 1 });

  if (reportRateLimitMap.size > 1000) {
    for (const [key, value] of reportRateLimitMap) {
      if (now - value.windowStart > REPORT_LIMIT_WINDOW_MS) {
        reportRateLimitMap.delete(key);
      }
    }
  }

  return { allowed: true };
}

export default async function handler(req, res) {
  // Only allow POST
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Support both the proper server-side env and the older frontend-prefixed
  // variable so production can recover even if only the legacy key exists.
  const apiKey = process.env.RESEND_API_KEY || process.env.VITE_RESEND_API_KEY;
  if (!apiKey) {
    return res.status(500).json({
      error: 'Email service not configured. Add RESEND_API_KEY to your Vercel environment variables.'
    });
  }

  const resend = new Resend(apiKey);

  try {
    const authClaims = await requireFirebaseAuth(req);
    const { to, projectName, totalValue, attachments } = req.body;
    const uid = String(authClaims?.user_id || authClaims?.sub || '').trim();
    const email = String(authClaims?.email || '').trim().toLowerCase();
    const ip = getClientIp(req);
    const identity = `${uid || email || ip || 'authenticated'}:send-report`;
    const limit = checkReportRateLimit(identity);

    if (!limit.allowed) {
      return res.status(429).json({
        error: 'You are sending reports too quickly. Please wait a moment before trying again.',
        retryAfterMs: limit.retryAfterMs,
      });
    }

    const normalizedRecipient = String(to || '').trim().toLowerCase();
    const safeProjectName = String(projectName || '').trim();

    if (!normalizedRecipient || !safeProjectName) {
      return res.status(400).json({ error: 'Missing required fields: to, projectName' });
    }

    if (!EMAIL_REGEX.test(normalizedRecipient)) {
      return res.status(400).json({ error: 'Please provide a valid recipient email address.' });
    }

    if (!email) {
      return res.status(401).json({ error: 'Authentication required.' });
    }

    if (attachments && !Array.isArray(attachments)) {
      return res.status(400).json({ error: 'Attachments must be provided as an array.' });
    }

    if ((attachments || []).length > 5) {
      return res.status(400).json({ error: 'A maximum of 5 attachments is allowed.' });
    }

    // Build attachment objects for Resend
    const resendAttachments = (attachments || []).map((att, index) => {
      const filename = String(att?.filename || '').trim();
      const content = String(att?.content || '').trim();

      if (!filename || !content) {
        throw new Error(`Attachment ${index + 1} is missing a filename or file content.`);
      }

      if (content.length > 5_000_000) {
        throw new Error(`Attachment ${index + 1} is too large.`);
      }

      return {
        filename,
        content,
      };
    });

    const fromAddress = process.env.RESEND_FROM_EMAIL || 'Quantra <onboarding@quantra-extimator.xyz>';

    const { data, error } = await resend.emails.send({
      from: fromAddress,
      to: [normalizedRecipient],
      subject: `BOQ Report: ${safeProjectName}`,
      text: [
        'BOQ Report',
        `Project: ${safeProjectName}`,
        totalValue ? `Estimated Contract Sum: N${Number(totalValue).toLocaleString()}` : null,
        resendAttachments.length > 0 ? `Attachments: ${resendAttachments.length}` : null,
        '',
        'Generated by Quantra Enterprise.'
      ].filter(Boolean).join('\n'),
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #f8fafc; padding: 0;">
          <!-- Header -->
          <div style="background: #0f172a; padding: 32px 24px; text-align: center;">
            <h1 style="color: white; margin: 0; font-size: 20px; font-weight: 800; letter-spacing: 0.02em;">
              Quantra
            </h1>
            <p style="color: #64748b; margin: 4px 0 0; font-size: 12px;">
              Digital Engineering Standards Platform
            </p>
          </div>

          <!-- Body -->
          <div style="padding: 32px 24px;">
            <h2 style="color: #0f172a; font-size: 18px; margin: 0 0 8px;">
              Bill of Quantities Report
            </h2>
            <p style="color: #64748b; font-size: 14px; line-height: 1.6; margin: 0 0 24px;">
              Please find attached the BOQ report for the project detailed below.
            </p>

            <!-- Project Card -->
            <div style="background: white; border: 1px solid #e2e8f0; border-radius: 12px; padding: 20px; margin-bottom: 24px;">
              <div style="margin-bottom: 12px;">
                <span style="font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em;">
                  PROJECT
                </span>
                <p style="font-size: 16px; font-weight: 700; color: #0f172a; margin: 4px 0 0;">
                  ${escapeHtml(safeProjectName)}
                </p>
              </div>
              ${totalValue ? `
              <div style="border-top: 1px solid #f1f5f9; padding-top: 12px;">
                <span style="font-size: 11px; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.05em;">
                  ESTIMATED CONTRACT SUM
                </span>
                <p style="font-size: 20px; font-weight: 800; color: #2563eb; margin: 4px 0 0;">
                  ₦${Number(totalValue).toLocaleString()}
                </p>
              </div>
              ` : ''}
            </div>

            ${resendAttachments.length > 0 ? `
            <p style="color: #64748b; font-size: 13px; margin: 0 0 4px;">
              📎 <strong>${resendAttachments.length}</strong> file(s) attached
            </p>
            ` : ''}
          </div>

          <!-- Footer -->
          <div style="background: #f1f5f9; border-top: 1px solid #e2e8f0; padding: 16px 24px; text-align: center;">
            <p style="color: #94a3b8; font-size: 11px; margin: 0;">
              Generated by Quantra Enterprise • Digital Engineering Standards
            </p>
          </div>
        </div>
      `,
      attachments: resendAttachments,
    });

    if (error) {
      console.error('Resend error:', error);
      return res.status(500).json({ error: error.message || 'Failed to send email' });
    }

    return res.status(200).json({ success: true, id: data?.id });
  } catch (err) {
    console.error('Send report error:', err);
    return res.status(Number(err.status || 500)).json({ error: err.message || 'Internal server error' });
  }
}
